[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
serde = {version="1.0.136", features=["derive"]}
jwt = "0.16.0"
hmac="0.12.1"
sha2 = "0.10.2"